import type { AstroComponent } from "@lucide/astro";
import { LinkTypes, QualificationTypes } from "../constants";
import {
  Users,
  Calendar,
  Layers,
  ArrowRight,
  ArrowLeft,
  User,
  ExternalLink,
  Menu,
  Linkedin,
  Globe,
  Plus,
  Trash2,
  Newspaper,
  GraduationCap,
  ThumbsUp,
  Briefcase,
  Trophy,
  Vote,
  House,
  LogOut,
  CircleQuestionMark,
  Square,
  SquareCheck,
  Check,
  SquareCheckBig,
  Share,
  GripVertical,
} from "@lucide/astro";

import {
  Facebook,
  Threads,
  Instagram,
  Youtube,
  Wikipedia,
  X,
  Tiktok,
} from "simple-icons-astro";

export {
  Users,
  User,
  Calendar,
  Layers,
  ExternalLink,
  Menu,
  ArrowRight,
  ArrowLeft,
  X,
  Linkedin,
  Globe,
  Plus,
  Trash2,
  Facebook,
  Threads,
  Tiktok,
  Instagram,
  Youtube,
  Wikipedia,
  House,
  LogOut,
  Vote,
  CircleQuestionMark,
  Square,
  SquareCheck,
  Check,
  SquareCheckBig,
  Share,
  GripVertical,
};

export const qualificationTypeToIcon: Record<string, AstroComponent> = {
  [QualificationTypes.EDUCATION]: GraduationCap,
  [QualificationTypes.WORK_EXPERIENCE]: Briefcase,
  [QualificationTypes.POLITICAL_EXPERIENCE]: Vote,
  [QualificationTypes.ENDORSEMENT]: ThumbsUp,
  [QualificationTypes.AWARD]: Trophy,
  [QualificationTypes.OTHER]: ExternalLink,
};

export const linkTypeToIcon: Record<string, AstroComponent> = {
  [LinkTypes.FACEBOOK]: Facebook,
  [LinkTypes.LINKEDIN]: Linkedin,
  [LinkTypes.INSTAGRAM]: Instagram,
  [LinkTypes.YOUTUBE]: Youtube,
  [LinkTypes.THREADS]: Threads,
  [LinkTypes.X]: X,
  [LinkTypes.WEBSITE]: Globe,
  [LinkTypes.WIKIPEDIA]: Wikipedia,
  [LinkTypes.OTHER]: ExternalLink,
  [LinkTypes.NEWS]: Newspaper,
  [LinkTypes.TIKTOK]: Tiktok,
};
